FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

LABEL maintainer="Noji Ryogo <rnoji@gmail.com>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# python install
RUN apt-get install -y curl python3.7 python3.7-dev python3.7-distutils
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
RUN update-alternatives --set python /usr/bin/python3.7
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&     python get-pip.py --force-reinstall &&     rm get-pip.py


# pip install
RUN pip install -U pip
RUN pip install --upgrade pip
RUN pip install torch==1.7.1 torchvision==0.8.2
RUN pip install opencv-python==4.4.0.46
RUN pip install numpy
RUN pip install matplotlib
RUN pip install pandas
RUN pip install tqdm
RUN pip install jupyter jupyter-contrib-nbextensions jupyter_nbextensions_configurator


# duser setting
ARG USER_ID
ARG GROUP_ID
RUN addgroup --gid  duser &&     adduser --disabled-password --gecos '' --uid  --gid  duser &&     adduser duser sudo &&     echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER duser
WORKDIR /home/duser/